version: "3"

services:
  web:
    image: localhost:5000/webapp:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  database:
    image: localhost:5000/webdb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "dockdeploytest"
      MYSQL_DATABASE: "webtest"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: